#서버포트 지정
server:
  port: 8010
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat :
    uri-encoding : UTF-8

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  security:
    user:
      name: test
      password : 1234
    oauth2:      client:        registration:
          google:
            client-id: 74722917616-86tf70r1kngreq027ujmrbi24c8dmqb5.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 472260130930847
            client-secret: 6ffd113521f0db371e5eb8af28c05a40
            scope:
              - email
              - public_profile          naver:
            client-id: Wbqht0isxUmQxDXYe6w6
            client-secret: K64InylIBD 
            scope:            - email
            - name
            - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8010/login/oauth2/code/naver
        provider:          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize  #요청
            token-uri:  https://nid.naver.com/oauth2.0/token             #token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response    #회원정보를 json으로 전달할때 response라는 key값으로 데이터를 전달해준다.
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://121.175.150.249:3306/project_20220113_01?useUnicode=true
    username : tp220113_01
    password : "0486"
mybatis:
  mapper-locations:
    - /mappers/*.xml

